migcom: do not include <machine/_types.h> from the build system
r329165 moved __va_list from <machine/_types.h> to <sys/_types.h>
and its definition is not present in our "${.OBJDIR}../../sys/sys/_types.h" either.

Since we improperly include <machine/_types.h> from the build machine, we
get it from neither header and the build fails:

--- parser.o ---
cc -O2 -pipe  -I/usr/home/saper/src/nextbsd/usr.bin/migcom -I/usr/home/saper/src/nextbsd/usr.bin/migcom/shims -I/usr/home/saper/src/nextbsd/usr.bin/migcom/../../include -I/usr/home/saper/src/nextbsd/usr.bin/migcom/../../sys -DYY_NO_UNPUT -g -MD  -MF.depend.parser.o -MTparser.o -std=gnu99  -Qunused-arguments  -I/build/obj/nextbsd/usr/home/saper/src/nextbsd/tmp/legacy/usr/include -c parser.c -o parser.o
--- parser.o ---
In file included from /usr/home/saper/src/nextbsd/usr.bin/migcom/parser.y:196:
/usr/home/saper/src/nextbsd/usr.bin/migcom/../../include/stdio.h:68:9: error: unknown type name '__va_list'
typedef __va_list       va_list;
        ^
/usr/home/saper/src/nextbsd/usr.bin/migcom/../../include/stdio.h:281:6: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
            __va_list);